name: Build Project

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Project

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gralde
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      - name: Publish Unit Test Results
        # Version 1.32
        uses: EnricoMi/publish-unit-test-result-action@0c8c54b3a1700e3d97e2efc1ccd68316af0eb6f6
        if: always()
        with:
          files: ./**/build/test-results/test/**/*.xml