name: Build Project

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Project

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

  publish:
    runs-on: ubuntu-latest
    name: Publish Project
    needs: build

    steps:

      - name: Publish gradle plugin(s)
        # Main branch only
        if: github.ref_name == 'main'
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publishPlugins
